Repository AY2223S1-CS2103T-W08-3/tp, pull requests merged in 2022-11, with the labels that each got.

#197 Joeyi Add Test cases and Update UG, DG, and PPP
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/team/jjoeyi.md
  src/test/java/seedu/address/logic/commands/TemplateCommandTest.java
  src/test/java/seedu/address/logic/parser/TemplateCommandParserTest.java
  src/test/java/seedu/address/model/person/LocationTest.java
  src/test/java/seedu/address/model/tag/TagTest.java
Labels: documentation

#199 Fix sorting by Name and moduleCode
  src/main/java/seedu/address/model/person/ModuleCode.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/Professor.java
  src/main/java/seedu/address/model/person/Student.java
  src/main/java/seedu/address/model/person/TeachingAssistant.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/test/java/seedu/address/model/person/ModuleCodeTest.java
Labels: type.Bug

#198 fix error message thrown
  docs/team/normkoh.md
  src/main/java/seedu/address/commons/util/CsvUtil.java
  src/test/data/CsvUtilTest/NullEmail.csv
  src/test/data/CsvUtilTest/NullName.csv
  src/test/data/CsvUtilTest/NullPhone.csv
  src/test/data/CsvUtilTest/ValidProfNoTags.csv
  src/test/data/CsvUtilTest/ValidProfessorNoOfficeHour.csv
  src/test/data/CsvUtilTest/ValidProfessorOfficeHour.csv
  src/test/data/CsvUtilTest/ValidStudent.csv
  src/test/data/CsvUtilTest/ValidStudentNoTags.csv
  src/test/data/CsvUtilTest/ValidTa.csv
  src/test/java/seedu/address/commons/util/CsvUtilTest.java
Labels: type.Bug

#200 Enforce stricter file name regex
  src/main/java/seedu/address/commons/core/filename/FileName.java
  src/test/java/seedu/address/commons/util/core/filename/FileNameTest.java
Labels: type.Bug

#196 Nitant-Test edit
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/model/person/OfficeHour.java
  src/main/java/seedu/address/model/person/Person.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/EditPersonDescriptorTest.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ProfCommandParserTest.java
  src/test/java/seedu/address/logic/parser/StudentCommandParserTest.java
  src/test/java/seedu/address/logic/parser/TaCommandParserTest.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/PersonUtil.java
  src/test/java/seedu/address/testutil/ProfessorBuilder.java
  src/test/java/seedu/address/testutil/StudentBuilder.java
  src/test/java/seedu/address/testutil/TeachingAssistantBuilder.java
  src/test/java/seedu/address/testutil/TypicalIndexes.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: type.Bug, severity.High

#203 Nitant-Update PPP
  docs/team/nitant-p.md
Labels: documentation

#202 Nitant-Improve code quality
  src/main/java/seedu/address/model/person/PersonMatchesPredicate.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/storage/JsonAdaptedProfessor.java
  src/main/java/seedu/address/storage/JsonAdaptedStudent.java
  src/main/java/seedu/address/storage/JsonAdaptedTeachingAssistant.java
Labels: type.Task

#204 update UG for sort and module code
  docs/UserGuide.md
  docs/images/AfterModuleCodeA.png
  docs/images/AfterSortName.png
  docs/images/AfterSortNameDesc.png
  docs/images/AppAndData.png
  docs/images/BeforeModuleCode.png
  docs/images/BeforeSortName.png
  docs/images/CsvExport.png
  docs/images/EnterExport.png
  docs/images/ExportFilePath.png
  docs/images/ExportSuccessful.png
  docs/images/ImportCommand.png
  docs/images/ImportFileField.png
  docs/images/SameLevel.png
  docs/images/SortReverse.png
  docs/images/SortSameLevel.png
Labels: documentation

#194 Jonas update ppp
  build.gradle
  docs/AboutUs.md
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/ModelClassDiagram.puml
  docs/diagrams/StorageClassDiagram.puml
  docs/images/AfterNameAscendingSort.png
  docs/images/AfterNameDescendingSort.png
  docs/images/BeforeSort.png
  docs/images/ModelClassDiagram.png
  docs/images/StorageClassDiagram.png
  docs/images/Ui.png
  docs/team/jonaspng.md
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/logic/commands/StudentCommand.java
  src/main/java/seedu/address/model/person/GithubUsername.java
  src/main/java/seedu/address/model/person/OfficeHour.java
  src/main/java/seedu/address/model/person/Rating.java
  src/main/java/seedu/address/model/person/Specialisation.java
  src/main/java/seedu/address/model/person/Year.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
Labels: documentation

#205 update DG for import command and included use case
  docs/DeveloperGuide.md
Labels: documentation

#206 update PPP
  docs/team/garethong.md
Labels: documentation

#208 Gareth update UG
  docs/UserGuide.md
  docs/images/AfterSortName.png
  docs/images/AfterSortNameDesc.png
  docs/images/AppAndData.png
  docs/images/BeforeSortName.png
  docs/images/CsvExport.png
  docs/images/EnterExport.png
  docs/images/ExportFilePath.png
  docs/images/ImportCommand.png
  src/main/java/seedu/address/logic/parser/FindCommandParser.java
Labels: documentation

#209 Fix DG
  docs/DeveloperGuide.md
  docs/team/jjoeyi.md
Labels: documentation

#210 restrict sorting to only sort by module code or name
  docs/UserGuide.md
  src/main/java/seedu/address/commons/core/order/Order.java
  src/main/java/seedu/address/logic/commands/SortCommand.java
  src/main/java/seedu/address/logic/parser/SortCommandParser.java
  src/test/java/seedu/address/logic/parser/SortCommandParserTest.java
Labels: type.Bug

#211 Jonas final ug
  docs/UserGuide.md
Labels: documentation

#212 Update PPP and DG
  docs/DeveloperGuide.md
  docs/diagrams/GithubCommandSequenceDiagram.puml
  docs/diagrams/StudentCommandSequenceDiagram.puml
  docs/images/GithubCommandSequenceDiagram.png
  docs/images/StudentCommandSequenceDiagram.png
  docs/team/jonaspng.md
Labels: documentation

#216 final PPP
  docs/team/garethong.md
Labels: documentation

#217 Nitant-update-dg-ppp
  docs/team/nitant-p.md
Labels: documentation
