Repository AY2223S1-CS2103T-W08-3/tp, pull requests merged in 2022-10, with the labels that each got.

#35 Nitant - update edit command tests
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
Labels: priority.Medium

#37 Add location field
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/ProfCommand.java
  src/main/java/seedu/address/logic/commands/StudentCommand.java
  src/main/java/seedu/address/logic/commands/TaCommand.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/ProfCommandParser.java
  src/main/java/seedu/address/logic/parser/StudentCommandParser.java
  src/main/java/seedu/address/logic/parser/TaCommandParser.java
  src/main/java/seedu/address/model/person/Location.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/Professor.java
  src/main/java/seedu/address/model/person/Student.java
  src/main/java/seedu/address/model/person/TeachingAssistant.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/storage/JsonAdaptedPersonDeserializer.java
  src/main/java/seedu/address/storage/JsonAdaptedProfessor.java
  src/main/java/seedu/address/storage/JsonAdaptedStudent.java
  src/main/java/seedu/address/storage/JsonAdaptedTeachingAssistant.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/view/PersonListCard.fxml
  src/test/java/seedu/address/commons/core/ConfigTest.java
  src/test/java/seedu/address/commons/core/VersionTest.java
  src/test/java/seedu/address/commons/util/ConfigUtilTest.java
  src/test/java/seedu/address/commons/util/JsonUtilTest.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/AddCommandIntegrationTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/FindCommandTest.java
  src/test/java/seedu/address/logic/commands/StudentCommandTest.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/CommandParserTestUtil.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/logic/parser/FindCommandParserTest.java
  src/test/java/seedu/address/model/AddressBookTest.java
  src/test/java/seedu/address/model/person/NameContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
  src/test/java/seedu/address/model/person/UniquePersonListTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/storage/JsonAddressBookStorageTest.java
  src/test/java/seedu/address/storage/JsonSerializableAddressBookTest.java
  src/test/java/seedu/address/storage/JsonUserPrefsStorageTest.java
  src/test/java/seedu/address/testutil/Assert.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/PersonUtil.java
  src/test/java/seedu/address/testutil/ProfessorBuilder.java
  src/test/java/seedu/address/testutil/StudentBuilder.java
  src/test/java/seedu/address/testutil/TeachingAssistantBuilder.java
  src/test/java/seedu/address/ui/TestFxmlObject.java
Labels: priority.High, type.Story

#39 Add sort function
  src/main/java/seedu/address/logic/commands/SortLexicographicalCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/UniquePersonList.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/SortLexicographicalCommandTest.java
  src/test/java/seedu/address/logic/commands/StudentCommandTest.java
  src/test/java/seedu/address/model/AddressBookTest.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: priority.Medium

#49 Nitant-Enhance Find
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/parser/FindCommandParser.java
  src/main/java/seedu/address/model/person/NameContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/person/PersonMatchesPredicate.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/FindCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/FindCommandParserTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/model/person/PersonMatchesPredicateTest.java
  src/test/java/seedu/address/testutil/PersonUtil.java
Labels: priority.High, type.Story, type.Enhancement

#43 Jonas modify clear all command
  src/main/java/seedu/address/logic/commands/ClearCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/test/java/seedu/address/logic/commands/ClearCommandTest.java
  src/test/java/seedu/address/logic/commands/StudentCommandTest.java
Labels: priority.Medium

#48 Modify delete command to take in multiple inputs
  src/main/java/seedu/address/commons/core/index/Index.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/parser/DeleteCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/DeleteCommandParserTest.java
  src/test/java/seedu/address/testutil/TypicalSetsOfIndex.java
Labels: priority.Medium, type.Enhancement

#42 Make location field optional for Professor, Student, and TA
  src/main/java/seedu/address/logic/commands/ProfCommand.java
  src/main/java/seedu/address/logic/commands/StudentCommand.java
  src/main/java/seedu/address/logic/commands/TaCommand.java
  src/main/java/seedu/address/logic/parser/Parser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/ProfCommandParser.java
  src/main/java/seedu/address/logic/parser/StudentCommandParser.java
  src/main/java/seedu/address/logic/parser/TaCommandParser.java
Labels: priority.Medium, type.Enhancement

#46 Gareth enhance sort
  src/main/java/seedu/address/commons/core/order/Order.java
  src/main/java/seedu/address/logic/commands/SortCommand.java
  src/main/java/seedu/address/logic/commands/SortLexicographicalCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/SortCommandParser.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/Professor.java
  src/main/java/seedu/address/model/person/Student.java
  src/main/java/seedu/address/model/person/TeachingAssistant.java
  src/main/java/seedu/address/model/person/UniquePersonList.java
  src/test/java/seedu/address/logic/commands/SortCommandTest.java
  src/test/java/seedu/address/logic/commands/StudentCommandTest.java
Labels: type.Enhancement

#51 Nitant-Fix edit command bug
  src/main/java/seedu/address/logic/commands/EditCommand.java
Labels: priority.Medium, type.Bug

#56 Differentiate between professor, TA and student
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/PersonListCard.fxml
Labels: priority.Medium, UI

#60 Enhance module code for student
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/StudentCommand.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/StudentCommandParser.java
  src/main/java/seedu/address/model/person/ModuleCode.java
  src/main/java/seedu/address/model/person/Student.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedModuleCode.java
  src/main/java/seedu/address/storage/JsonAdaptedPersonDeserializer.java
  src/main/java/seedu/address/storage/JsonAdaptedStudent.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/PersonListCard.fxml
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/testutil/StudentBuilder.java
Labels: type.Enhancement

#53 Jonas add GitHub field and github command
  docs/tutorials/RemovingFields.md
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/GithubCommand.java
  src/main/java/seedu/address/logic/commands/ProfCommand.java
  src/main/java/seedu/address/logic/commands/StudentCommand.java
  src/main/java/seedu/address/logic/commands/TaCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/GithubCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/ProfCommandParser.java
  src/main/java/seedu/address/logic/parser/StudentCommandParser.java
  src/main/java/seedu/address/logic/parser/TaCommandParser.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/person/Address.java
  src/main/java/seedu/address/model/person/GithubUsername.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/Professor.java
  src/main/java/seedu/address/model/person/Student.java
  src/main/java/seedu/address/model/person/TeachingAssistant.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/storage/JsonAdaptedPersonDeserializer.java
  src/main/java/seedu/address/storage/JsonAdaptedProfessor.java
  src/main/java/seedu/address/storage/JsonAdaptedStudent.java
  src/main/java/seedu/address/storage/JsonAdaptedTeachingAssistant.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/view/PersonListCard.fxml
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditPersonDescriptorTest.java
  src/test/java/seedu/address/logic/commands/GithubCommandTest.java
  src/test/java/seedu/address/model/person/AddressTest.java
  src/test/java/seedu/address/model/person/GithubUsernameTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/ProfessorBuilder.java
  src/test/java/seedu/address/testutil/StudentBuilder.java
  src/test/java/seedu/address/testutil/TeachingAssistantBuilder.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: priority.High

#54 Add Rating field for Professors and TAs
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/ProfCommand.java
  src/main/java/seedu/address/logic/commands/TaCommand.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/ProfCommandParser.java
  src/main/java/seedu/address/logic/parser/TaCommandParser.java
  src/main/java/seedu/address/model/person/Professor.java
  src/main/java/seedu/address/model/person/Rating.java
  src/main/java/seedu/address/model/person/TeachingAssistant.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/storage/JsonAdaptedPersonDeserializer.java
  src/main/java/seedu/address/storage/JsonAdaptedProfessor.java
  src/main/java/seedu/address/storage/JsonAdaptedStudent.java
  src/main/java/seedu/address/storage/JsonAdaptedTeachingAssistant.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/testutil/ProfessorBuilder.java
  src/test/java/seedu/address/testutil/TeachingAssistantBuilder.java
Labels: priority.Medium, type.Enhancement

#72 Jonas add student year and prof specialisation field
  build.gradle
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/GithubCommand.java
  src/main/java/seedu/address/logic/commands/ProfCommand.java
  src/main/java/seedu/address/logic/commands/StudentCommand.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/ProfCommandParser.java
  src/main/java/seedu/address/logic/parser/StudentCommandParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/person/GithubUsername.java
  src/main/java/seedu/address/model/person/ModuleCode.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/Professor.java
  src/main/java/seedu/address/model/person/Specialisation.java
  src/main/java/seedu/address/model/person/Student.java
  src/main/java/seedu/address/model/person/TeachingAssistant.java
  src/main/java/seedu/address/model/person/Year.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/storage/JsonAdaptedPersonDeserializer.java
  src/main/java/seedu/address/storage/JsonAdaptedProfessor.java
  src/main/java/seedu/address/storage/JsonAdaptedStudent.java
  src/main/java/seedu/address/storage/JsonAdaptedTeachingAssistant.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/view/PersonListCard.fxml
  src/test/java/seedu/address/logic/commands/StudentCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/FindCommandParserTest.java
  src/test/java/seedu/address/model/person/SpecialisationTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/PersonUtil.java
  src/test/java/seedu/address/testutil/ProfessorBuilder.java
  src/test/java/seedu/address/testutil/StudentBuilder.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: priority.High

#61 Gareth add sort command testing
  src/main/java/seedu/address/commons/core/order/Order.java
  src/test/java/seedu/address/commons/util/core/ConfigTest.java
  src/test/java/seedu/address/commons/util/core/VersionTest.java
  src/test/java/seedu/address/commons/util/core/index/IndexTest.java
  src/test/java/seedu/address/commons/util/core/order/OrderTest.java
  src/test/java/seedu/address/logic/commands/SortCommandTest.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: help wanted, type.Task

#63 Normkoh rating UI
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/model/person/Professor.java
  src/main/java/seedu/address/storage/JsonAdaptedProfessor.java
  src/main/java/seedu/address/storage/JsonAdaptedTeachingAssistant.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/images/FilledStar.png
  src/main/resources/images/emptystar.png
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/PersonListCard.fxml
Labels: priority.High, UI

#74 JoeYi Add template command
  src/main/java/seedu/address/logic/commands/CommandResult.java
  src/main/java/seedu/address/logic/commands/ProfCommand.java
  src/main/java/seedu/address/logic/commands/StudentCommand.java
  src/main/java/seedu/address/logic/commands/TaCommand.java
  src/main/java/seedu/address/logic/commands/TemplateCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/TemplateCommandParser.java
  src/main/java/seedu/address/ui/CommandBox.java
  src/main/java/seedu/address/ui/MainWindow.java
Labels: priority.Medium, type.Enhancement

#66 Nitant-Enhance find II
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/FindCommandParser.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/PersonMatchesPredicate.java
  src/main/java/seedu/address/model/person/Professor.java
  src/main/java/seedu/address/model/person/Student.java
  src/main/java/seedu/address/model/person/TeachingAssistant.java
  src/test/java/seedu/address/logic/commands/FindCommandTest.java
  src/test/java/seedu/address/logic/parser/FindCommandParserTest.java
  src/test/java/seedu/address/model/person/PersonMatchesPredicateTest.java
  src/test/java/seedu/address/testutil/PersonMatchesPredicateBuilder.java
  src/test/java/seedu/address/testutil/PersonUtil.java
Labels: priority.High, type.Enhancement

#76 Jonas update GitHub command DG
  docs/DeveloperGuide.md
  docs/diagrams/GithubCommandActivityDiagram.puml
  docs/diagrams/GithubCommandSequenceDiagram.puml
  docs/images/GithubCommandActivityDiagram.png
  docs/images/GithubCommandSequenceDiagram.png
Labels: documentation

#84 Nitant-DG find sequence
  docs/DeveloperGuide.md
  docs/diagrams/FindCommandSequenceDiagram.puml
  docs/images/FindCommandSequenceDiagram.png
Labels: documentation

#69 Add DeleteMultiple feature in DG
  docs/DeveloperGuide.md
  docs/diagrams/DeleteMultipleSequenceDiagram.puml
  docs/images/DeleteMultipleSequenceDiagram.png
Labels: documentation

#85 Gareth add office hour
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/ProfCommand.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/ProfCommandParser.java
  src/main/java/seedu/address/model/person/OfficeHour.java
  src/main/java/seedu/address/model/person/Professor.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedPersonDeserializer.java
  src/main/java/seedu/address/storage/JsonAdaptedProfessor.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/view/PersonListCard.fxml
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/testutil/PersonUtil.java
  src/test/java/seedu/address/testutil/ProfessorBuilder.java
Labels: type.Story

#80 Add Template Feature to DG
  docs/DeveloperGuide.md
  docs/diagrams/ttCommandSequenceDiagram.puml
  docs/images/ttCommandSequenceDiagram.png
  src/main/java/seedu/address/logic/parser/ParserUtil.java
Labels: documentation

#82 Nitant-Find by Rating, Specialisation and Year
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/parser/FindCommandParser.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/PersonMatchesPredicate.java
  src/main/java/seedu/address/model/person/Professor.java
  src/main/java/seedu/address/model/person/Student.java
  src/main/java/seedu/address/model/person/TeachingAssistant.java
Labels: priority.High, type.Enhancement

#88 Jonas debug office hours field
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/ProfCommandParser.java
  src/main/java/seedu/address/model/person/OfficeHour.java
  src/main/java/seedu/address/model/person/Professor.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/storage/JsonAdaptedProfessor.java
  src/main/java/seedu/address/storage/JsonAdaptedStudent.java
  src/main/java/seedu/address/storage/JsonAdaptedTeachingAssistant.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/test/java/seedu/address/testutil/ProfessorBuilder.java
Labels: type.Bug

#87 Gareth update Developer Guide for SortCommand
  docs/DeveloperGuide.md
  docs/diagrams/SortCommandActivityDiagram.puml
  docs/diagrams/SortCommandSequenceDiagram.puml
  docs/images/SortCommandActivityDiagram.png
  docs/images/SortCommandSequenceDiagram.png
Labels: documentation

#94 fix DG
  docs/DeveloperGuide.md
Labels: documentation, type.Bug

#95 Jonas edit ug and dg
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/ModelClassDiagram.puml
  docs/images/ModelClassDiagram.png
  src/main/java/seedu/address/storage/JsonAdaptedStudent.java
Labels: documentation

#91 Gareth fix office hour
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/person/OfficeHour.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedProfessor.java
  src/test/java/seedu/address/testutil/ProfessorBuilder.java
Labels: priority.High

#98 Change app icon and name
  src/main/java/seedu/address/ui/UiManager.java
  src/main/resources/images/soccat.png
  src/main/resources/view/MainWindow.fxml
  src/test/java/seedu/address/commons/util/AppUtilTest.java
Labels: priority.High, UI

#100 Normkoh add icons for fields
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/images/GitHub-Light.png
  src/main/resources/images/GitHub.png
  src/main/resources/images/email.png
  src/main/resources/images/locationbig.png
  src/main/resources/images/locationbig2.png
  src/main/resources/images/telephone.png
  src/main/resources/images/telephoneblack.png
  src/main/resources/view/PersonListCard.fxml
Labels: priority.Medium, UI

#93 Normkoh pie chart
  src/main/java/seedu/address/commons/core/GuiSettings.java
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/ClearCommand.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/ProfCommand.java
  src/main/java/seedu/address/logic/commands/StudentCommand.java
  src/main/java/seedu/address/logic/commands/TaCommand.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/Professor.java
  src/main/java/seedu/address/model/person/Student.java
  src/main/java/seedu/address/model/person/TeachingAssistant.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/PersonPieChart.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/PieChart.fxml
  src/test/java/seedu/address/logic/commands/StudentCommandTest.java
Labels: priority.High, UI

#104 Normkoh update UG with add and deleteMultiple features
  docs/DeveloperGuide.md
  docs/UserGuide.md
  src/main/resources/view/MainWindow.fxml
Labels: documentation

#107 Add User story
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: documentation

#102 Add TemplateCommand Test Cases
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/logic/commands/TemplateCommandTest.java
Labels: type.Task

#103 Update UG and template for Professor and Student
  docs/DeveloperGuide.md
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/ProfCommand.java
  src/main/java/seedu/address/logic/commands/StudentCommand.java
Labels: documentation

#111 Gareth add export
  build.gradle
  src/main/java/seedu/address/commons/core/filename/FileName.java
  src/main/java/seedu/address/commons/util/CsvUtil.java
  src/main/java/seedu/address/logic/commands/ExportCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/ExportCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/test/java/seedu/address/commons/util/core/filename/FileNameTest.java
  src/test/java/seedu/address/logic/commands/ExportCommandTest.java
Labels: type.Story

#115 fix export problem
  src/main/java/seedu/address/commons/util/CsvUtil.java
Labels: type.Bug, severity.High

#106 Nitant-Find office hours
  src/main/java/seedu/address/logic/parser/FindCommandParser.java
  src/main/java/seedu/address/model/person/OfficeHour.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/PersonMatchesPredicate.java
  src/main/java/seedu/address/model/person/Professor.java
  src/main/java/seedu/address/model/person/Student.java
  src/main/java/seedu/address/model/person/TeachingAssistant.java
Labels: priority.High, type.Story, type.Enhancement

#118 Nitant-UG & DG: Update Find
  docs/DeveloperGuide.md
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/FindCommand.java
Labels: documentation, priority.High

#119 Gareth update Developer's Guide
  .gitignore
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/ExportCommandSequenceDiagram.puml
  docs/diagrams/SortCommandSequenceDiagram.puml
  docs/images/ExportCommandSequenceDiagram.png
Labels: documentation

#116 update .gitignore to ignore export directory
  .gitignore
Labels: type.Task

#113 add testing for office hour regex
  src/test/java/seedu/address/model/person/OfficeHourTest.java
Labels: type.Bug

#101 fix edit moduleCode
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
Labels: help wanted, priority.High, type.Bug

#117 Gareth edit User Guide
  docs/UserGuide.md
  docs/images/AfterNameAscendingSort.png
  docs/images/AfterNameDescendingSort.png
  docs/images/BeforeSort.png
  docs/images/CSVfile.png
  docs/images/ExportSuccessful.png
  docs/images/SortModuleCodeAscending.png
  docs/images/SortModuleCodeDescending.png
Labels: documentation

#109 Jonas Update Draft UG&DG
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/images/UiPiechart.png
Labels: documentation

#120 Jonas Update UG 2
  docs/UserGuide.md
Labels: documentation

#122 add import function
  docs/diagrams/ExportCommandSequenceDiagram.png
  src/main/java/seedu/address/commons/util/CsvUtil.java
  src/main/java/seedu/address/logic/commands/ExportCommand.java
  src/main/java/seedu/address/logic/commands/ImportCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/ImportCommandParser.java
Labels: type.Story

#125 Debug edit command
  src/main/java/seedu/address/logic/commands/EditCommand.java
Labels: type.Bug, severity.Medium

#126 Jonas update ug&dg3
  docs/UserGuide.md
  docs/_config.yml
  docs/_sass/minima/_base.scss
  docs/images/AfterImport.jpg
  docs/images/BeforeImport.jpg
  docs/images/ImportFileLocation.jpg
  docs/images/NestedImportFile.jpg
  src/main/java/seedu/address/logic/commands/FindCommand.java
Labels: documentation

#129 Fix Pie Chart
  src/main/java/seedu/address/model/ModelManager.java
Labels: type.Bug, severity.Medium

#131 Debug import command
  src/main/java/seedu/address/commons/util/CsvUtil.java
Labels: type.Bug, severity.High

#133 Nitant-Fix UG find
  docs/UserGuide.md
Labels: documentation, priority.High, type.Bug

#192 Nitant-Test find & Fix Bugs
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/parser/FindCommandParser.java
  src/main/java/seedu/address/model/person/GithubUsername.java
  src/main/java/seedu/address/model/person/PersonMatchesPredicate.java
  src/main/java/seedu/address/model/person/Professor.java
  src/main/java/seedu/address/model/person/Student.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/FindCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/FindCommandParserTest.java
  src/test/java/seedu/address/model/person/PersonMatchesPredicateTest.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/PersonMatchesPredicateBuilder.java
  src/test/java/seedu/address/testutil/PersonUtil.java
  src/test/java/seedu/address/testutil/ProfessorBuilder.java
  src/test/java/seedu/address/testutil/StudentBuilder.java
  src/test/java/seedu/address/testutil/TeachingAssistantBuilder.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: priority.High, type.Bug
